// Generated by Bisonc++ V4.13.01 on Sat, 28 Jan 2017 15:31:22 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {274, 2}, // 1: program ->  declaration_list procedure_definition
     {275, 1}, // 2: declaration_list ->  procedure_declaration
     {275, 2}, // 3: declaration_list ->  variable_declaration_list procedure_declaration
     {275, 2}, // 4: declaration_list ->  procedure_declaration variable_declaration_list
     {277, 5}, // 5: procedure_declaration (VOID) ->  VOID NAME '(' ')' ';'
     {276, 9}, // 6: procedure_definition (NAME) ->  NAME '(' ')' #0001 '{' optional_variable_declaration_list #0002 statement_list '}'
     {278, 0}, // 7: #0001 ->  <empty>
     {279, 0}, // 8: #0002 ->  <empty>
     {280, 0}, // 9: optional_variable_declaration_list ->  <empty>
     {280, 1}, // 10: optional_variable_declaration_list ->  variable_declaration_list
     {281, 1}, // 11: variable_declaration_list ->  variable_declaration
     {281, 2}, // 12: variable_declaration_list ->  variable_declaration_list variable_declaration
     {282, 2}, // 13: variable_declaration (';') ->  declaration ';'
     {283, 2}, // 14: declaration (INTEGER) ->  INTEGER NAME
     {283, 2}, // 15: declaration (FLOAT) ->  FLOAT NAME
     {284, 0}, // 16: statement_list ->  <empty>
     {284, 2}, // 17: statement_list ->  statement_list assignment_statement
     {285, 4}, // 18: assignment_statement (ASSIGN) ->  variable ASSIGN arith_expression ';'
     {286, 0}, // 19: arith_expression ->  <empty>
     {287, 1}, // 20: operand ->  arith_expression
     {288, 1}, // 21: expression_term ->  variable
     {288, 1}, // 22: expression_term ->  constant
     {289, 1}, // 23: variable (NAME) ->  NAME
     {290, 1}, // 24: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {290, 1}, // 25: constant (DOUBLE_NUMBER) ->  DOUBLE_NUMBER
     {291, 1}, // 26: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 10} },                             
    { {       274}, {  1} }, // program                  
    { {       275}, {  2} }, // declaration_list         
    { {       277}, {  3} }, // procedure_declaration    
    { {       281}, {  4} }, // variable_declaration_list
    { {       265}, {  5} }, // VOID                     
    { {       282}, {  6} }, // variable_declaration     
    { {       283}, {  7} }, // declaration              
    { {       262}, {  8} }, // INTEGER                  
    { {       263}, {  9} }, // FLOAT                    
    { {         0}, {  0} },                             
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, {  3} },                        
    { {       276}, { 10} }, // procedure_definition
    { {       259}, { 11} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  6} },                             
    { {     281}, { 12} }, // variable_declaration_list
    { {     282}, {  6} }, // variable_declaration     
    { {     283}, {  7} }, // declaration              
    { {     262}, {  8} }, // INTEGER                  
    { {     263}, {  9} }, // FLOAT                    
    { {       0}, { -2} },                             
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, {  7} },                         
    { {       277}, { 13} }, // procedure_declaration
    { {       282}, { 14} }, // variable_declaration 
    { {       265}, {  5} }, // VOID                 
    { {       283}, {  7} }, // declaration          
    { {       262}, {  8} }, // INTEGER              
    { {       263}, {  9} }, // FLOAT                
    { {         0}, {  0} },                         
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       259}, { 15} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_6[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 16} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       259}, { 17} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       259}, { 18} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 19} }, // '('
    { {         0}, {  0} },       
};

SR__ s_12[] =
{
    { { REQ_DEF}, {  5} },                        
    { {     282}, { 14} }, // variable_declaration
    { {     283}, {  7} }, // declaration         
    { {     262}, {  8} }, // INTEGER             
    { {     263}, {  9} }, // FLOAT               
    { {       0}, { -4} },                        
};

SR__ s_13[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 20} }, // '('
    { {         0}, {  0} },       
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 21} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 22} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_21[] =
{
    { { DEF_RED}, {  2} },         
    { {     278}, { 23} }, // #0001
    { {       0}, { -7} },         
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 24} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 25} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_24[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_25[] =
{
    { { REQ_DEF}, {  7} },                                      
    { {     280}, { 26} }, // optional_variable_declaration_list
    { {     281}, { 27} }, // variable_declaration_list         
    { {     282}, {  6} }, // variable_declaration              
    { {     283}, {  7} }, // declaration                       
    { {     262}, {  8} }, // INTEGER                           
    { {     263}, {  9} }, // FLOAT                             
    { {       0}, { -9} },                                      
};

SR__ s_26[] =
{
    { { DEF_RED}, {  2} },         
    { {     279}, { 28} }, // #0002
    { {       0}, { -8} },         
};

SR__ s_27[] =
{
    { { REQ_DEF}, {   5} },                        
    { {     282}, {  14} }, // variable_declaration
    { {     283}, {   7} }, // declaration         
    { {     262}, {   8} }, // INTEGER             
    { {     263}, {   9} }, // FLOAT               
    { {       0}, { -10} },                        
};

SR__ s_28[] =
{
    { { DEF_RED}, {   2} },                  
    { {     284}, {  29} }, // statement_list
    { {       0}, { -16} },                  
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  5} },                        
    { {       125}, { 30} }, // '}'                 
    { {       285}, { 31} }, // assignment_statement
    { {       289}, { 32} }, // variable            
    { {       259}, { 33} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_30[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       264}, { 34} }, // ASSIGN
    { {         0}, {  0} },          
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {   2} },                    
    { {     286}, {  35} }, // arith_expression
    { {       0}, { -19} },                    
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 36} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

// $insert defaultactionreturn
                            // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 50 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         program_object.set_procedure(current_procedure, get_line_number());
         program_object.global_list_in_proc_check();
         }
         }
        break;

        case 2:
#line 63 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = new Symbol_Table();
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 3:
#line 73 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = d_vsp__[-1].symbol_table;
         CHECK_INVARIANT((global_table != NULL), "Global declarations cannot be null");
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 4:
#line 86 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = d_vsp__[0].symbol_table;
         CHECK_INVARIANT((global_table != NULL), "Global declarations cannot be null");
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 5:
#line 100 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-3].string_value != NULL), "Procedure name cannot be null");
         CHECK_INVARIANT((*d_vsp__[-3].string_value == "main"), "Procedure name must be main in declaration");
         }
         }
        break;

        case 6:
#line 143 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Sequence_Ast* seq = d_vsp__[-1].sequence_ast;
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         CHECK_INVARIANT((seq != NULL), "statement list cannot be null");
         current_procedure->set_sequence_ast(*seq);
         }
         }
        break;

        case 7:
#line 111 "parser.yy"
        d_val__ = d_vsp__[-2];
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-2].string_value != NULL), "Procedure name cannot be null");
         CHECK_INVARIANT((*d_vsp__[-2].string_value == "main"), "Procedure name must be main");
         string proc_name = *d_vsp__[-2].string_value;
         current_procedure = new Procedure(void_data_type, proc_name, get_line_number());
         CHECK_INPUT ((program_object.variable_in_symbol_list_check(proc_name) == false),
         "Procedure name cannot be same as global variable", get_line_number());
         }
         }
        break;

        case 8:
#line 127 "parser.yy"
        d_val__ = d_vsp__[-5];
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         Symbol_Table * local_table = d_vsp__[0].symbol_table;
         if (local_table == NULL)
         local_table = new Symbol_Table();
         current_procedure->set_local_list(*local_table);
         }
         }
        break;

        case 9:
#line 157 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.symbol_table = NULL;
         }
         }
        break;

        case 10:
#line 165 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].symbol_table != NULL), "Declaration statement list cannot be null here");
         d_val__.symbol_table = d_vsp__[0].symbol_table;
         }
         }
        break;

        case 11:
#line 177 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table_Entry * decl_stmt = d_vsp__[0].symbol_entry;
         CHECK_INVARIANT((decl_stmt != NULL), "Non-terminal declaration statement cannot be null");
         string decl_name = decl_stmt->get_variable_name();
         CHECK_INPUT ((program_object.variable_proc_name_check(decl_name) == false),
         "Variable name cannot be same as the procedure name", get_line_number());
         if(current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != decl_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         Symbol_Table * decl_list = new Symbol_Table();
         decl_list->push_symbol(decl_stmt);
         d_val__.symbol_table = decl_list;
         }
         }
        break;

        case 12:
#line 202 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         
         Symbol_Table_Entry * decl_stmt = d_vsp__[0].symbol_entry;
         Symbol_Table * decl_list = d_vsp__[-1].symbol_table;
         CHECK_INVARIANT((decl_stmt != NULL), "The declaration statement cannot be null");
         CHECK_INVARIANT((decl_list != NULL), "The declaration statement list cannot be null");
         string decl_name = decl_stmt->get_variable_name();
         CHECK_INPUT((program_object.variable_proc_name_check(decl_name) == false),
         "Procedure name cannot be same as the variable name", get_line_number());
         if(current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != decl_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         CHECK_INPUT((decl_list->variable_in_symbol_list_check(decl_name) == false), 
         "Variable is declared twice", get_line_number());
         decl_list->push_symbol(decl_stmt);
         d_val__.symbol_table = decl_list;
         }
         }
        break;

        case 13:
#line 234 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         pair<Data_Type, string> * decl = d_vsp__[-1].decl;
         CHECK_INVARIANT((decl != NULL), "Declaration cannot be null");
         Data_Type type = decl->first;
         string decl_name = decl->second;
         Symbol_Table_Entry * decl_entry = new Symbol_Table_Entry(decl_name, type, get_line_number());
         d_val__.symbol_entry = decl_entry;
         }
         }
        break;

        case 14:
#line 254 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         }
         }
        break;

        case 15:
#line 262 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         }
         }
        break;

        case 16:
#line 272 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         }
         }
        break;

        case 17:
#line 280 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         }
         }
        break;

        case 18:
#line 292 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         }
         }
        break;

        case 20:
#line 309 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         }
         }
        break;

        case 21:
#line 319 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         }
         }
        break;

        case 22:
#line 327 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         }
         }
        break;

        case 23:
#line 337 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table_Entry * var_table_entry;
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Variable name cannot be null");
         if (current_procedure->variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = &(current_procedure->get_symbol_table_entry(*d_vsp__[0].string_value));
         else if (program_object.variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = &(program_object.get_symbol_table_entry(*d_vsp__[0].string_value));
         else
         CHECK_INPUT_AND_ABORT(CONTROL_SHOULD_NOT_REACH, "Variable has not been declared", get_line_number());
         d_val__.ast = new Name_Ast(*d_vsp__[0].string_value, *var_table_entry, get_line_number());
         delete d_vsp__[0].string_value;
         }
         }
        break;

        case 24:
#line 362 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         }
         }
        break;

        case 25:
#line 370 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         }
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



